### ISSUE TITLE
Engine won't build; release doesn't run

### ISSUE THREAD

**Issue by jdbrody** [riddlesio/ultimate-tic-tac-toe-engine#6]
I'm having trouble building the engine on a Gentoo Linux box.  When I type
`gradle build jar`  it fails with the following

`test bot 0 test case Hull

io.riddles.javainterface.exception.TerminalException: Failed to parse configuration
	at io.riddles.javainterface.engine.AbstractEngine.parseInputUntilStart(AbstractEngine.java:166)
	at io.riddles.javainterface.engine.AbstractEngine.willRun(AbstractEngine.java:85)
	at io.riddles.tictactoe.TicTacToeEngineSpec.test bot 0 test case Hull(TicTacToeEngineSpec.groovy:292)`

When I try to run the ultimate-tic-tac-toe-engine-1.0.5.jar from either build/libs or the relases tab, it prints `Aug 22, 2017 6:02:55 PM io.riddles.javainterface.engine.AbstractEngine willRun
INFO: Setting up engine. Waiting for initialize...` and then hangs.

Any help greatly appreciated!

**Comment by JimVanEeden** [comment]
Can you post what command you use to run the match and also the contents of your wrapper-commands.json?

**Comment by jdbrody** [comment]
Hi Jim,
Thanks for the prompt reply.  
I'm running it with 
`$ java -jar ultimate-tic-tac-toe-engine-1.0.5.jar "$(cat wrapper-commands.json)"`
and the following wrapper-commands.json 



{
  "wrapper": {
    "timebankMax": 10000,
    "timePerMove": 100,
    "maxTimeouts": 0,
    "resultFile": "./resultfile.json",
    "debug": true
  },
  "match": {
    "bots": [{
      "command": "python3 /home/justin/ai/source/ultimate-tic-tac-toe-python-starter/main.py"
    },{
      "command": "python3 /home/justin/ai/source/ultimate-tic-tac-toe-python-starter/main.py"
    }],
    "engine": {
      "command": "java -jar /home/justin/ai/source/ultimate-tic-tac-toe-engine/ultimate-tic-tac-toe-engine-1.0.5.jar"
    }
  }
}

**Comment by JimVanEeden** [comment]
Ok so your problem is you have to run that match-wrapper.jar with the wrapper-commands and that program starts the bots and the engine.

It seems your wrapper-commands should just work fine, so you're gonna have to run it with:

`java -jar match-wrapper-1.3.2.jar "$(cat wrapper-commands.json)"`

**Comment by jdbrody** [comment]
That is what it says to do in the instructions!  For some reason that didn't seem to be working before but  is working now -- thanks for the help!!
